BlogEngine/Models/User.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;

namespace BlogEngine.Models
{
    public class User : IdentityUser
    {
        [JsonIgnore]
        public virtual List<Blog> Blogs { get; set; }

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<User> manager)
        {
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            return userIdentity;
        }
    }
}

BlogEngine/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using BlogEngine.Models;
using PagedList;

namespace BlogEngine.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        // GET: AdminBlogs
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                return View(db.Blogs.ToList());
            }
            string userId = User.Identity.GetUserId();
            return View(db.Blogs.Where(b => b.Author.Id == userId).ToList());
        }

        [AllowAnonymous]
        public ActionResult List(int? page)
        {
            return View(this.ListBlogs(page));
        }

        private IPagedList<Blog> ListBlogs(int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return db.Blogs.Where(b => b.Approved == true).OrderBy(b => b.Id).ToPagedList(pageNumber, pageSize);
        }

        // GET: AdminBlogs/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = null;
            if (User.IsInRole("Admin"))
            {
                blog = db.Blogs.Find(id);
            }
            else
            {
                string userId = User.Identity.GetUserId();
                blog = db.Blogs.Where(b => b.Id == id && b.Author.Id == userId).SingleOrDefault();
            }
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: AdminBlogs/Create
        public ActionResult Create()
        {
            ViewBag.Tags = this.GetTagsList();
            return View();
        }

        // POST: AdminBlogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Content,Approved,Tags,TagsId")] Blog blog)
        {
            List<Tag> allTags = this.GetTagsList();
            if (ModelState.IsValid)
            {
                blog.Author = db.Users.Find(User.Identity.GetUserId());
                var tags = db.Tags.Where(m => blog.TagsId.Contains(m.Id)).ToList();
                blog.Tags = tags;
                if (!User.IsInRole("Admin"))
                {
                    blog.Approved = false;
                }
                if (User.IsInRole("Admin") && blog.Approved)
                {
                    foreach (Tag t in blog.Tags) { t.Approved = true; }
                }
                db.Blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Tags = allTags;
            return View(blog);
        }

        // GET: AdminBlogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = null;
            if (User.IsInRole("Admin"))
            {
                blog = db.Blogs.Find(id);
            }
            else
            {
                string userId = User.Identity.GetUserId();
                blog = db.Blogs.Where(b => b.Id == id && b.Author.Id == userId).Single();
            }
            if (blog == null)
            {
                return HttpNotFound();
            }
            ViewBag.Tags = this.GetTagsList(blog.Tags.ToList());
            return View(blog);
        }

        // POST: AdminBlogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Content,Approved,Tags,TagsId")] Blog blog)
        {
            string userId = User.Identity.GetUserId();
            if (!User.IsInRole("Admin") && blog.Author != null && !blog.Author.Id.Equals(userId))
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                db.Blogs.Attach(blog);
                using (var dbCtx = new BlogDbContext())
                { 
                    Blog existingBlog = dbCtx.Blogs.Find(blog.Id);
                    List<Tag> deletedTags = existingBlog.Tags.Where(t => !blog.TagsId.Contains(t.Id)).ToList<Tag>();
                    List<Tag> addedTags = dbCtx.Tags.Where(m => blog.TagsId.Contains(m.Id)).ToList<Tag>();
                    deletedTags.ForEach(t => existingBlog.Tags.Remove(t));
                    foreach (Tag t in addedTags)
                    {
                        existingBlog.Tags.Add(t);
                        if (User.IsInRole("Admin") && blog.Approved)
                        {
                            t.Approved = true;
                        }
                    }
                    dbCtx.SaveChanges();
                }
                if (!User.IsInRole("Admin"))
                {
                    blog.Approved = false;
                }
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Tags = this.GetTagsList(blog.Tags);
            return View(blog);
        }

        // GET: AdminBlogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = null;
            if (User.IsInRole("Admin"))
            {
                blog = db.Blogs.Find(id);
            }
            else
            {
                string userId = User.Identity.GetUserId();
                blog = db.Blogs.Where(b => b.Id == id && b.Author.Id == userId).Single();
            }
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: AdminBlogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = null;
            if (User.IsInRole("Admin"))
            {
                blog = db.Blogs.Find(id);
            }
            else
            {
                blog = db.Blogs.Where(b => b.Id == id && b.Author.Id == User.Identity.GetUserId()).Single();
            }
            if (blog == null)
            {
                return HttpNotFound();
            }
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected List<Tag> GetTagsList(List<Tag> tags = null) 
        {
            if (tags != null && tags.Count() > 0)
            {
                List<int> tagsId = tags.Select(t => t.Id).ToList();
                return db.Tags.Where(t => t.Approved == true || tagsId.Contains(t.Id)).OrderBy(t => t.Value).ToList();
            }
            return db.Tags.Where(t => t.Approved == true).OrderBy(t => t.Value).ToList();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogEngine/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogEngine.Models;

namespace BlogEngine.Controllers
{
    [Authorize(Roles="Admin")]
    public class UserController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        // GET: AdminUsers
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: AdminUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: AdminUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: AdminUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: AdminUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: AdminUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: AdminUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogEngine/Views/User/Create.cshtml
@model BlogEngine.Models.User

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EmailConfirmed)
                    @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumberConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PhoneNumberConfirmed)
                    @Html.ValidationMessageFor(model => model.PhoneNumberConfirmed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TwoFactorEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TwoFactorEnabled)
                    @Html.ValidationMessageFor(model => model.TwoFactorEnabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LockoutEndDateUtc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LockoutEndDateUtc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LockoutEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LockoutEnabled)
                    @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccessFailedCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccessFailedCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccessFailedCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogEngine/Views/User/Delete.cshtml
@model BlogEngine.Models.User

@{
    ViewBag.Title = "Delete user: " + Html.DisplayFor(model => model.UserName);
}

<h2>@ViewBag.Title</h2>

<div class="alert alert-danger">
    <p>Are you sure you want to delete the following user?</p>
    <p><strong>@Html.DisplayFor(model => model.UserName)</strong> (@Html.DisplayFor(model => model.Email))</p>
</div>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color btn-group">
        <input type="submit" value="Delete" class="btn btn-primary" />
        @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-default" })
    </div>
}

BlogEngine/Views/User/Details.cshtml
@model BlogEngine.Models.User

@{
    ViewBag.Title = "User details: " + Html.DisplayFor(model => model.UserName);
}

<h2>@ViewBag.Title</h2>

<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <tbody>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Email)</th>
                <td>@Html.DisplayFor(model => model.Email)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(model => model.UserName)</th>
                <td>@Html.DisplayFor(model => model.UserName)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Blogs)</th>
                <td>
                    <ul>
                        @foreach (BlogEngine.Models.Blog blog in Model.Blogs)
                        {
                            <li>@Html.ActionLink(blog.Title, "Details", "Blog", new { id = blog.Id }, new { })</li>
                        }
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</div>
     
<p class="btn-group">
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-default" })
</p>

BlogEngine/Views/User/Edit.cshtml
@model BlogEngine.Models.User

@{
    ViewBag.Title = "Edit user: " + Html.DisplayFor(model => model.UserName);
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 btn-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogEngine/Views/User/Index.cshtml
@model IEnumerable<BlogEngine.Models.User>

@{
    ViewBag.Title = "Users management";
}

<h2>@ViewBag.Title</h2>

<p class="btn-group btn-group-justified">
    @Html.ActionLink("Add new blog article", "Create", new { }, new { @class = "btn btn-primary" })
</p>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    <div class="btn-group btn-group-xs">
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-default" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                    </div>
                </td>
            </tr>
        }

    </table>
</div>